# Generated by Django 4.1.4 on 2022-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='material',
            name='is_private',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extended_access',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='disk_path',
            field=models.FilePathField(match='{|\\.docx$|\\.xls$|\\.pdf$|\\.pptx$|\\.ppt$|\\.pptm$|\\.png$|\\.jpeg$|}', path='materials/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
