# Generated by Django 4.1.4 on 2022-12-16 18:04

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_material_access_level_remove_user_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=0)),
                ('name', models.CharField(max_length=30, validators=[api.models.validate_document_name_length])),
                ('disk_path', models.FilePathField(match='{|\\.docx$|\\.xls$|\\.pdf$|\\.pptx$|\\.ppt$|\\.pptm$|\\.png$|\\.jpeg$|}', path='materials/<django.db.models.fields.related.ForeignKey>')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=20, validators=[api.models.validate_folder_name_length]),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='document',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.folder'),
        ),
    ]
